(SIMP-9659) Add scheduling options
simp/pupmod-simp-aide pull request #77
Opened 2021-06-10 14:39 UTC by trevor-vaughan

- Changed
  - Default to `systemd` for scheduling
  - Use `--check` instead of `-C` by default to match what most scanners expect
  - Randomize the minute field so that I/O load is reduced on hosting platforms
- Added
  - Allow users to choose between the following options:
    - `systemd` => Default - Use systemd timers
    - `root`    => Legacy - Update root's crontab
    - `etc`     => Scanner Compat - Update /etc/crontab using Augeas
  - When one method is chosen, the others will be disabled

SIMP-9659 #close
SIMP-9261 #close

2021-06-10 15:02 UTC, trevor-vaughan commented
This will need to be pushed to remove the Puppet 5 tests  - Check the GitLab tests

2021-06-10 16:15 UTC, lnemsick-simp requested changes
IMHO the cron defaults should remain in the init.pp.
Did **not** deep-dive into the augeas rules as I have no domain knowledge. Am relying on the corresponding acceptance tests.

2021-06-10 16:15 UTC, lnemsick-simp commented on manifests/init.pp
> +  Optional[Enum['root', 'etc', 'systemd']] $cron_method       = undef,
Which cron method is being selected?  Not clear here. Without a default, seems like no cron of any type will be run.

2021-06-10 16:15 UTC, lnemsick-simp commented on manifests/set_schedule.pp
> +  systemd::timer { 'puppet_aide.timer':
This resource is being created even when the user selects another option.  I understand that this systemd timer is disabled if not using 'systemd' cron method, but other design pattern of resource ensure absent is being used the rest of the file.  Why was this method used instead? Does it not apply to the system:timer resource?

2021-06-10 16:15 UTC, lnemsick-simp commented on CHANGELOG
> +- Added
Should indicate that it adds Puppet 7 support

2021-06-11 11:49 UTC, lnemsick-simp approved these changes
Review comments largely addressed

2021-06-11 11:51 UTC, merged